module.exports = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_VENDOR: 'REGISTER_VENDOR',
  
  SEND_USER_PAYWORD_CERTIFICATE: 'SEND_USER_PAYWORD_CERTIFICATE',
  SEND_VENDOR_CERTIFICATE: 'SEND_VENDOR_CERTIFICATE',
  
  SEND_COMMIT: 'SEND_COMMIT',
  SEND_PAY: 'SEND_PAY',

  

}
